# Generated by Django 6.0.5 on 2026-06-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("type", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("date_spend", models.DateField(auto_now_add=True, db_index=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
