# Generated by Django 6.0.5 on 2026-06-17 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def normalize_monthly_obligations(apps, schema_editor):
    MonthlyObligation = apps.get_model("spendings", "MonthlyObligation")
    type_map = {
        "payroll": "Зарплаты",
        "cloud": "ИИ сервисы",
        "office_rent": "Аренда офиса",
        "other": "Другое",
    }

    for obligation in MonthlyObligation.objects.all():
        obligation.charge_day = obligation.due_date.day if obligation.due_date else 1
        obligation.type = type_map.get(obligation.type, obligation.type)
        obligation.save(update_fields=("charge_day", "type"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("spendings", "0003_monthlyobligation"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyobligation",
            name="charge_day",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="monthlyobligation",
            name="excluded_for",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="monthlyobligation",
            name="last_charged_for",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="monthlyobligation",
            name="last_spending",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monthly_obligation_charges",
                to="spendings.spending",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyobligation",
            name="type",
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.RunPython(normalize_monthly_obligations, noop_reverse),
    ]
