# Generated by Django 6.0.5 on 2026-06-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboards", "0003_alter_taskperformance_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboard",
            name="name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
