# Generated by Django 6.0.5 on 2026-06-15 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_task_status(apps, schema_editor):
    Task = apps.get_model("onboards", "Task")
    Task.objects.filter(approval_status="cancelled").update(status="cancelled")
    Task.objects.filter(is_active=False).exclude(
        approval_status="cancelled",
    ).update(status="done")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("onboards", "0005_task_approval_status_task_cancelled_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="approval_action",
            field=models.CharField(
                blank=True,
                choices=[("create", "Create"), ("cancel", "Cancel")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="approval_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="approval_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_task_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To do"),
                    ("in_progress", "In progress"),
                    ("in_review", "In review"),
                    ("done", "Done"),
                    ("cancelled", "Cancelled"),
                ],
                default="todo",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="taskauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("approval_requested", "Approval requested"),
                    ("cancellation_requested", "Cancellation requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("assigned", "Assigned"),
                    ("unassigned", "Unassigned"),
                    ("attachment_added", "Attachment added"),
                    ("attachment_removed", "Attachment removed"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(backfill_task_status, noop),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="task_attachments/%Y/%m/%d/")),
                ("file_name", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[("file", "File"), ("voice", "Voice")],
                        default="file",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="onboards.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
    ]
