# Generated by Django 6.0.5 on 2026-06-01 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=120)),
                ("date_start", models.DateField(default=datetime.date.today)),
                ("date_end", models.DateField()),
                ("deal_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("cash", "Cash"), ("card", "Card"), ("loan", "Loan")],
                        max_length=4,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("payment_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DealFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DealPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField(default=datetime.date.today)),
                ("delayed", models.BooleanField(default=False)),
            ],
        ),
    ]
