# Generated by Django 6.0.5 on 2026-06-01 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"role": "collaborator"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dealfile",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="deals.deal"
            ),
        ),
        migrations.AddField(
            model_name="dealpayment",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="deals.deal"
            ),
        ),
    ]
