# Generated by Django 6.0.5 on 2026-06-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0003_alter_deal_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealfile",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="deals.deal",
            ),
        ),
        migrations.AlterField(
            model_name="dealfile",
            name="file",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="dealpayment",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="deals.deal",
            ),
        ),
    ]
