# Generated by Django 6.0.5 on 2026-06-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0004_alter_dealfile_deal_alter_dealfile_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="deal_amount",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
