# Generated by Django 6.0.5 on 2026-06-15 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_primary_user_to_collaborators(apps, schema_editor):
    Deal = apps.get_model("deals", "Deal")
    db_alias = schema_editor.connection.alias

    for deal in Deal.objects.using(db_alias).exclude(user_id__isnull=True):
        deal.collaborators.add(deal.user_id)


def clear_primary_user_collaborators(apps, schema_editor):
    Deal = apps.get_model("deals", "Deal")
    db_alias = schema_editor.connection.alias

    for deal in Deal.objects.using(db_alias).exclude(user_id__isnull=True):
        deal.collaborators.remove(deal.user_id)


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0005_alter_deal_deal_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "collaborator"},
                related_name="collaborator_deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            copy_primary_user_to_collaborators,
            clear_primary_user_collaborators,
        ),
        migrations.AlterField(
            model_name="deal",
            name="user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "collaborator"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
