# Generated by Django 6.0.5 on 2026-06-17 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0006_deal_collaborators_alter_deal_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="name",
            field=models.CharField(blank=True, default="", max_length=180),
        ),
        migrations.AddField(
            model_name="deal",
            name="responsibles",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "employee"},
                related_name="responsible_deals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dealfile",
            name="file",
            field=models.FileField(upload_to="deal_files/%Y/%m/%d/"),
        ),
        migrations.CreateModel(
            name="DealLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("url", models.URLField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="deals.deal",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="DealStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateField(blank=True, null=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="deals.deal",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "employee"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deal_stages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
    ]
