# Generated by Django 6.0.5 on 2026-06-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0007_deal_name_deal_responsibles_alter_dealfile_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealstage",
            name="parent_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_stages",
                to="deals.dealstage",
            ),
        ),
    ]
