# Generated by Django 6.0.5 on 2026-07-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0008_dealstage_parent_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
