# Generated by Django 6.0.5 on 2026-06-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
