# Generated by Django 6.0.5 on 2026-06-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=120)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=20)),
                ("tasks_can_edit", models.BooleanField(default=False)),
                ("tasks_can_delete", models.BooleanField(default=False)),
                ("tasks_can_create", models.BooleanField(default=False)),
                ("accounting_can_retrieve", models.BooleanField(default=False)),
                ("deals_can_create", models.BooleanField(default=False)),
                ("deals_can_delete", models.BooleanField(default=False)),
                ("deals_can_update", models.BooleanField(default=False)),
            ],
        ),
    ]
