# Generated by Django 6.0.5 on 2026-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employees_can_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="employees_can_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="employees_can_update",
            field=models.BooleanField(default=False),
        ),
    ]
