# Generated by Django 6.0.5 on 2026-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_employees_can_create_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="accounting_can_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="accounting_can_update",
            field=models.BooleanField(default=False),
        ),
    ]
