# Generated by Django 6.0.5 on 2026-06-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employee_accounting_can_create_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employees_can_see_salary",
            field=models.BooleanField(default=False),
        ),
    ]
