# Generated by Django 6.0.5 on 2026-06-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employee_employees_can_see_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="accounting_can_delete",
            field=models.BooleanField(default=False),
        ),
    ]
