# Generated by Django 6.0.5 on 2026-06-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_employee_accounting_can_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="wallets_can_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="wallets_can_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="wallets_can_update",
            field=models.BooleanField(default=False),
        ),
    ]
