# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_remove_employee_employees_can_see_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="wallets_can_view_balance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="deals_can_view_amount",
            field=models.BooleanField(default=False),
        ),
    ]
