# Generated by Django 6.0.5 on 2026-07-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0010_employee_sales_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="clients_can_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="clients_can_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="clients_can_retrieve",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="clients_can_update",
            field=models.BooleanField(default=False),
        ),
    ]
