# Generated by Django 6.0.5 on 2026-06-09 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date_earned",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
    ]
